name: build

env:
  TARGET_SOLUTION_VAR: 'FilmHouse.sln'
  DOTNET_VERSION: '7.0.x'

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with dotnet
        working-directory: ./src
        run: |
          echo ${{ github.head_ref }}.${{ github.sha }}
          dotnet clean $TARGET_SOLUTION_VAR
          dotnet restore $TARGET_SOLUTION_VAR
          dotnet build $TARGET_SOLUTION_VAR -m:1 --no-restore /warnaserror
