name: pull-request

env:
  WORKING_DIR: ./src
  TARGET_SOLUTION_VAR: 'FilmHouse.sln'
  DOTNET_VERSION: '7.0.x'

on:
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup mysql
        uses: shogo82148/actions-setup-mysql@v1.28.1
        with:
          distribution: "mysql"
          mysql-version: "8.0"
          root-password: "Tony19811031"
          user: "sa"
          password: "Tony19811031"
          run: mysql -uroot -e 'SELECT version()'
          
      - name: Restore NuGet packages
        working-directory: ${{ env.WORKING_DIR }}
        run: nuget restore ${{ env.TARGET_SOLUTION_VAR }}

      - name: Build with dotnet
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          dotnet clean ${{ env.TARGET_SOLUTION_VAR }}
          dotnet restore ${{ env.TARGET_SOLUTION_VAR }}
          dotnet build ${{ env.TARGET_SOLUTION_VAR }} -m:1 --no-restore /warnaserror

      - name: Run NUnit tests
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          dotnet restore ${{ env.TARGET_SOLUTION_VAR }}
          dotnet test ${{ env.TARGET_SOLUTION_VAR }} --no-build --verbosity normal --logger "trx;LogFileName=TestResult.xml"

      - name: Check test results
        working-directory: ${{ env.WORKING_DIR }}
        id: test-results
        run: echo "::set-output name=tests-passed::$(find . -name 'TestResult.xml' -type f -exec grep -i ' outcome=\"Passed\"' {} + | wc -l)"

      - name: Last
        id: is-ok
        run: echo "Tests Passed:${{ steps.test-results.outputs.tests-passed }}"